name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        # Execute unit tests
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
        # Execute instrumented tests
      - name: Espresso tests
        uses: faruktoptas/android-github-actions-emulator@1.1.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
        # Generate an Apk
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Debug APK
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
